#!/usr/bin/env bash
# Generated by the ai-plugin-sdk build. Edit the plugin's own sources instead.

# The plugin these libraries were built for. Nothing else here names it.

PLUGIN_NAME='repository-confinement'
PLUGIN_PREFIX='REPOSITORY_CONFINEMENT'
PLUGIN_DISPLAY_NAME='repository-confinement'

plugin_setting_default() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' '{state}/notes' ;;
    UPDATE_CHECK) printf '%s' 'on' ;;
    UPDATE_CHECK_DAYS) printf '%s' '1' ;;
    VERSION_SOURCE) printf '%s' 'https://raw.githubusercontent.com/justinkek/repository-confinement/main/package.json' ;;
    WRITE_SCOPE) printf '%s' 'worktree' ;;
    SCRATCHPAD_PATHS) printf '%s' '/tmp/claude-*/scratchpad:/tmp/claude-*/tasks:/private/tmp/claude-*/scratchpad:/private/tmp/claude-*/tasks' ;;
    STATE_PATHS) printf '%s' '' ;;
    CONFIG_PATHS) printf '%s' '~/.claude:~/.claude-*' ;;
    PASTED_IMAGE_PATHS) printf '%s' '/tmp/claude-*:/private/tmp/claude-*' ;;
  esac
}

plugin_setting_kind() {
  case "$1" in
    STOP_NOTE_DIRECTORY) printf '%s' 'text' ;;
    UPDATE_CHECK) printf '%s' 'switch' ;;
    UPDATE_CHECK_DAYS) printf '%s' 'count' ;;
    VERSION_SOURCE) printf '%s' 'text' ;;
    WRITE_SCOPE) printf '%s' 'choice' ;;
    SCRATCHPAD_PATHS) printf '%s' 'text' ;;
    STATE_PATHS) printf '%s' 'text' ;;
    CONFIG_PATHS) printf '%s' 'text' ;;
    PASTED_IMAGE_PATHS) printf '%s' 'text' ;;
  esac
}

plugin_setting_values() {
  case "$1" in
    WRITE_SCOPE) printf '%s' 'worktree repository' ;;
  esac
}

plugin_session_start_hooks() {
  :
}
